- backend.cpp
fix glfw context when goroutine switches threads #29
> fix glfw context #29

- examples/main.go
> Example: Fix texture, spelling, and error message

- cmd/codegen/gengo.go
Hi there!
It is a small fix in debug output in cmd/codegen
> cmd/codegen: improve debug information

- cmd/codegen/gengo.go
- cmd/codegen/return_wrapper.go
> codegen: returnWraper does not need FuncDefs arg anymore

- cimgui_enums.go
- cmd/codegen/gengo.go
> codegen: trim trailing _ suffix in enums

- backend.go
- cimgui_funcs.go
- cimplot_funcs.go
- cmd/codegen/arg_wrapper.go
- cmd/codegen/gengo.go
- cmd/codegen/return_wrapper.go
- examples/main.go
- extra_types.go
- input_text.go
- texture.go
- util.go
- vector_helpers.go
- vector_helpers_test.go
> Extra types: trim im/ImGui prefix

- extra_types.go
Add conversions from and to `color.Color` and `uint32`.
> Add conversions for Color

- cimgui_funcs.go
- cimplot_funcs.go
- cmd/codegen/arguments_wrapper.go
- cmd/codegen/gengo_funcs.go
- cmd/codegen/return_wrapper.go
I've siplified code of `args_wrapper.go` and `return_wrapper.go` reducing its size about 50% :smile:
> codegen: refactor

- .github/dependabot.yml
- .github/workflows/golangci-lint.yaml
- .golangci.yml
> Setup linter

- extra_types.go
- texture.go
> extra types: fix data race issues

- cimgui_funcs.go
- cimplot_funcs.go
- cmd/codegen/gengo_funcs.go
some function sdidn't work as expected (fix #89), some was broken by #93 (finishers was called before C call)
this PR is intended to fix both bugs mentioned above
> Hotfix: finishers strategy

- cimplot_funcs.go
- cimplot_wrapper.cpp
- cimplot_wrapper.h
- cmd/codegen/arguments_wrapper.go
- cmd/codegen/gencpp.go
- cmd/codegen/gengo.go
> implot internal support

- cimgui_funcs.go
- cimplot_funcs.go
- cmd/codegen/arguments_wrapper.go
- cmd/codegen/gengo_funcs.go
as a result: about ~5k less code lines (I love to remove code :upside_down_face: )
> Fix newlines

- cimgui_funcs.go
- cmd/codegen/arguments_wrapper.go
- extra_types.go
- extra_types.h
- input_text.go
> extra types: fix C type in plot time

- Makefile
> makefile: update: checkout branches before generating

- clipboard.go
> Add helper to install clipboard callbacks

- cimgui_funcs.go
- cimplot_funcs.go
- cmd/codegen/gengo_funcs.go
> codegen: consider non-pointer arguments of auto-generated struct type

- cmd/codegen/flags.go
- cmd/codegen/gengo_funcs.go
- cmd/codegen/main.go
- go.mod
- go.sum
> Improve logging

- backend.go
- glfw_backend.cpp
- glfw_backend.go
- glfw_backend.h
> backend: add SetWindowPos

- backend.go
- examples/main.go
- glfw_backend.go
> backend: remove dependency on GLFWBackend

- cimgui_funcs.go
- cimgui_structs.go
- cimplot_funcs.go
- cimplot_structs.go
- cmd/codegen/arguments_wrapper.go
- cmd/codegen/gengo_structs.go
- cmd/codegen/return_wrapper.go
- ensure that field name written with PascalCase
- add some missing argument/return types
> Structgen fixes

- .gitignore
- Makefile
- cmd/codegen/go.mod
- cmd/codegen/go.sum
- go.mod
- go.sum
> codegen: make a separated module

- backend.go
- examples/main.go
- glfw_backend.cpp
- glfw_backend.go
- glfw_backend.h
> Add set icons to backend

- backend.go
- glfw_backend.cpp
- glfw_backend.go
- glfw_backend.h
> Backend add callbacks

- cimgui_funcs.go
- cimgui_structs.go
- cimplot_funcs.go
- cmd/codegen/return_wrapper.go
update status of #184 bug -> enhancement
> Workaround input text

- cimgui_funcs.go
- cimnodes_funcs.go
- cimplot_funcs.go
- cmd/codegen/arguments_wrapper.go
- cmd/codegen/function_deffiniton.go
- cmd/codegen/gencpp.go
- cmd/codegen/gengo_funcs.go
This PR adds RemoveFinisher parameter to ArgDef struct. I set it for all auto-generated struct setters,.
This fixes #87 
Also close #196 (no longer needed as root case is fixed)
> Finishers refactor

- .github/workflows/golangci-lint.yaml
- .github/workflows/test.yaml
- cimgui_funcs.go
- cimgui_structs.go
- cimplot_funcs.go
- cimplot_structs.go
- cmd/codegen/arguments_wrapper.go
- extra_types.go
- go.mod
(need to upgrade go to 1.21 everywhere)
> vectors: use runtime.Pinner to pin vector data

- cimgui_funcs.go
- cimgui_structs.go
- cimplot_funcs.go
- cmd/codegen/arguments_wrapper.go
- cmd/codegen/return_wrapper.go
- templates/dummy.go.template
- type_wrapper.go
fix #184 :tada: progress on #90 (maybe fixed too? - gonna check on giu PR)
I got an idea to just ignore this pinner panic :smile: and it worked :tada:
> Fix void ptr arg

- .github/workflows/test.yaml
- cimgui.go
MacOS job on giu crashes. I need to know if cimgui-go compiles then.
> workflow: add macos

- cimgui_structs_accessor.cpp
- cimplot_funcs.go
- cimplot_structs_accessor.cpp
- cimplot_structs_accessor.h
- cmd/codegen/gencpp.go
> Gencpp bugfix

- glfw_backend.go
- glfw_backend.h
> hotfix: fix naming

- cimgui_wrapper.cpp
- cmd/codegen/gencpp.go
> Fix strings being cut short by 1 char

- cimgui_funcs.go
- cmd/codegen/gengo_funcs.go
> Funcs comments generator

- glfw_backend.cpp
fix https://github.com/AllenDang/cimgui-go/issues/279
> glfw: fix DeleteTexture implementation

- cimgui_enums.go
- cimmarkdown_enums.go
- cimnodes_enums.go
- cimplot_enums.go
- cmd/codegen/gengo_enums.go
> codegen: enforce type on enums constants

- backend/sdlbackend/sdl_backend.go
- examples/sdl/main.go
Tested on an M2 Air - Darwin Kernel Version 23.6.0
> Add frameworks to the SDL2 Darwin build so the example runs

- backend/sdlbackend/sdl_backend.cpp
Add in the missing afterRender callback that is present in other backends
> Sdlbackend add after render

- backend/ebiten-backend/ebiten_api.go
- backend/ebiten-backend/ebiten_backend.go
- examples/ebiten-game/README.md
- examples/ebiten-game/main.go
Hi
This example presents, how to use cimgui-go in your ebiten game (without using our backend mechanism)
> Examples: add ebiten game example

- cmd/codegen/arguments_wrapper.go
- cmd/codegen/return_wrapper.go
- imgui/cimgui_funcs.go
- immarkdown/cimmarkdown_funcs.go
- imnodes/cimnodes_funcs.go
- implot/cimplot_funcs.go
- implot/extra_types.go
generates more code
_merge after #319_
> Add some more types support

- README.md
Turns out we need to fix something to have A= :smile:
> readme: add badges on top

- README.md
> README: add awesome go badge

- go.mod
- go.sum
now depenabot's pr should work
> there was something wrong with go.mod

- cmd/codegen/arguments_wrapper.go
- cmd/codegen/return_wrapper.go
- imgui/cimgui_funcs.go
- implot/cimplot_funcs.go
- utils/helpers.go
- utils/ptr.go
- utils/vectors/vector.go
> Vectors rework

- cmd/codegen/arguments_wrapper.go
- cmd/codegen/gengo.go
- cmd/codegen/gengo_typedefs.go
- cmd/codegen/return_wrapper.go
- examples/common/common.go
- imgui/cimgui_funcs.go
- imgui/cimgui_typedefs.go
- imnodes/cimnodes_typedefs.go
- implot/cimplot_funcs.go
- implot/cimplot_typedefs.go
- internal/pool.go
resolve #224 
implementation details in https://github.com/AllenDang/cimgui-go/issues/224#issuecomment-2452156237
> Auto generated callbacks implementation

- ImGuiColorTextEdit/cimcte_funcs.go
- cmd/codegen/gengo_funcs.go
- cmd/codegen/return_wrapper.go
- imgui/cimgui_funcs.go
- imgui/cimgui_typedefs.go
- imguizmo/cimguizmo_funcs.go
- immarkdown/cimmarkdown_funcs.go
- imnodes/cimnodes_funcs.go
- implot/cimplot_funcs.go
- implot/cimplot_typedefs.go
> codegen: free source char* after C.GoString call

- cmd/codegen/arguments_wrapper.go
- cmd/codegen/gengo_callbacks.go
- cmd/codegen/return_wrapper.go
- imgui/cimgui_typedefs.go
- immarkdown/cimmarkdown_funcs.go
- immarkdown/cimmarkdown_typedefs.go
- implot/cimplot_typedefs.go
> Callbacks attempt 2: generate non-pointer callbacks

- ImGuiColorTextEdit/cimcte_typedefs.go
- cmd/codegen/gengo_typedefs.go
- imgui/cimgui_typedefs.go
- imguizmo/cimguizmo_typedefs.go
- immarkdown/cimmarkdown_typedefs.go
- imnodes/cimnodes_typedefs.go
- implot/cimplot_typedefs.go
> codegen: add NewEmptyXXX

- ImGuiColorTextEdit/cimcte_typedefs.go
- cmd/codegen/gengo_typedefs.go
- imgui/cimgui_typedefs.go
- imguizmo/cimguizmo_typedefs.go
- immarkdown/cimmarkdown_typedefs.go
- imnodes/cimnodes_typedefs.go
- implot/cimplot_typedefs.go
> Rename NewXXXEmpty -> NewEmptyXXX

- ImGuiColorTextEdit/cimcte_funcs.go
- cmd/codegen/gengo_funcs.go
- cmd/codegen/return_wrapper.go
- imgui/cimgui_funcs.go
- imgui/cimgui_typedefs.go
- imguizmo/cimguizmo_funcs.go
- immarkdown/cimmarkdown_funcs.go
- imnodes/cimnodes_funcs.go
- implot/cimplot_funcs.go
- implot/cimplot_typedefs.go
Reverts AllenDang/cimgui-go#379
> Revert "codegen: free source char* after C.GoString call"

- .github/workflows/golangci-lint.yaml
- .github/workflows/test.yaml
- go.mod
> mod: rquire latest golang 1.24.0

- utils/helpers.go
This method converts any pointer to slice with a given length
> utils: add PtrToSlice

- ImGuiColorTextEdit/funcs.go
- cmd/codegen/cimgui-go-preset.json
- cmd/codegen/gengo_funcs.go
- cmd/codegen/presets.go
- imgui/funcs.go
- immarkdown/funcs.go
- imnodes/funcs.go
- implot/funcs.go
> Custom finalizer

- backend/glfwbackend/glfw_backend.cpp
While using "github.com/AllenDang/cimgui-go/imgui" and trying out the imgui demo with "imgui.ShowDemoWindow()" I noticed that the application randomly stops generating frames. After analyzing the issue a bit I found out that moving the mouse generates more frames (up to 144 FPS because my monitor is 144hz) and breaks the frame timing. The longer the mouse is moved the bigger the gap before the next frame. Setting the framerate wtih "wnd.SetTargetFPS(144)" fixed the issue but increased the CPU usage while any other lower framerate caused the frame delay issue. The fix was rewriting the rendering loop for the glfw backend.
The new loop limits the framerate to what the user sets with "wnd.SetTargetFPS()". If a frame is completed faster than the allocated time for that frame the program …
> backend/glfw: Fix frame timing

- backend/ebiten-backend/backend_flags.go
- backend/ebiten-backend/cimgui_backend_impl.go
- backend/ebiten-backend/ebiten_backend.go
> ebitenbackend: add EbitenBackendFlagsTransparent

- backend/backend.go
- backend/ebiten-backend/cimgui_backend_impl.go
- backend/glfwbackend/glfw_backend.go
- backend/sdlbackend/sdl_backend.go
- backend/texture.go
- examples/common/common.go
- examples/ebiten-game-in-texture/main.go
> BREAKING: backend: use TextureRef instead of TextureID

- backend/ebiten-backend/ebiten_backend.go
fixes #473, progress on #470
this was a nice one ;-)
> ebitenbackend: pass modifiers to imguiIO

- backend/glfwbackend/glfw_backend.go
GLFWWindowMousePassthrough => GLFWWindowFlagsMousePassthrough
> glfwbackend: fix flag name
