- backend.cpp
- backend.go
- texture.go
This allows cimgui-go to "almost" be a drop-in replacement for [imgui-go](https://github.com/inkyblackness/imgui-go)
I choose to make the GLFW backend opt-in since that's what makes the most sense for my use-case, but depending on other uses it might be better to have it opt-out instead
> Make glfw backend optional

- cimgui_test.go
`CreateContext()` and `DestroyContext()` do not take arguments.
> test: Fix build & spelling

- backend.go
- cimgui_funcs.go
- cimplot_funcs.go
- cmd/codegen/arg_wrapper.go
- type_wrapper.go
> Wrapper: use generics

- cimgui_funcs.go
- cimplot_funcs.go
- cmd/codegen/gencpp.go
- cmd/codegen/gengo.go
- cmd/codegen/main.go
- cmd/codegen/return_wrapper.go
- extra_types.go
> codegen: return out value instead of taking pointer to it

- extra_types.go
its just cosmetical fix - it is more logical for a developer to see r, g, b, a (suggests color notation as RGBA nor HSV or CMYK) in color notation
> extra types: rename NewColor's args from x,y,z,w to r,g,b,a

- cimgui_funcs.go
- cimplot_funcs.go
- cmd/codegen/gengo.go
- cmd/codegen/gengo_funcs.go
since all the auto-generated structs are already uintptrs (what means they are pointer on C-side) we don't need pointer receivers in GO (because of #87)
close #87
> codegen: remove pointer receivers

- cimgui_funcs.go
- cimplot_funcs.go
- cmd/codegen/arguments_wrapper.go
- examples/main.go
imo it is more logical for programmers to say just &myArray than creating a new array with pointers to each element of our array
reffer #84
@AllenDang let me know if there was any reason for doing it this way.
> arg type: change type of array arguments from [n]*type -> *[n]type

- cimplot_funcs.go
- cimplot_structs.go
- cmd/codegen/arguments_wrapper.go
- cmd/codegen/gencpp.go
- cmd/codegen/gengo.go
- cmd/codegen/return_wrapper.go
- cmd/codegen/structures_deffinition.go
- extra_types.go
Implemented PlotTime as extra type.
extra method ` (i PlotTime) Time()` returns Go's native `time.Time`
It's required for these widgets:
- TimePicker
- DatePicker
> Implement PlotTime

- backend.cpp
- backend.go
- backend.h
Issue #108 
[glfwSetWindowShouldClose](https://www.glfw.org/docs/latest/group__window.html#ga49c449dde2a6f87d996f4daaa09d6708)
```
This function sets the value of the close flag of the specified window. This can be used to override the user's attempt to close the window, or to signal that it should be closed.
```
> add window.SetShouldClose method

- Makefile
- cimgui_funcs.go
- cimplot_funcs.go
gofumpt (https://github.com/mvdan/gofumpt) is a drop-in replacement for gofmt. It provides more stricted rules.
This change will make code in the project look better
> make: use gofumpt instead of gofmt

- cimgui_funcs.go
- cmd/codegen/arguments_wrapper.go
- extra_types.go
From `imgui.h`:
```
typedef int ImGuiKeyChord;          // -> ImGuiKey | ImGuiMod_XXX    // Flags: for storage only for now: an ImGuiKey optionally OR-ed with one or more ImGuiMod_XXX values.
```
This type is used by the (work in progress) Shortcut API.
It's a bit of a weird type... `ImGuiKey | ImGuiMod_*`, but `ImGuiMod_*` are already `ImGuiKey` and not a distinct type. Essentially it's an alias for the `ImGuiKey`, but with a different semantic meaning.
This PR adds a new simple wrapper for the type, but maybe it should just be a type alias for the existing `Key`?
> Add type KeyChord

- cimgui_funcs.go
- cimplot_funcs.go
- cmd/codegen/gengo_funcs.go
This makes it much easier to figure out what the default hints are for functions with many parameters.
It feels a bit hacking to split the arg after space to the get name. A better solution might be to change args from a `[]string` to a `[]Arg` type which contains both name and type. But that's a bigger design change
> Output parameter default hints in the same order as in the function

- cimgui_funcs.go
- cimgui_structs.go
- cimplot_funcs.go
- cimplot_structs.go
- cmd/codegen/structures_deffinition.go
Idk why was that restriction there, but after removing it, much more function is generated
> Codegen: remove Im* prefix restriction on structs

- type_wrapper.go
eg:
running on windows:
imgui.PlotPlotPieChartFloatPtrV cause window closed without any exception and stack dump
> fix issues/163 : call C.free on a GO pointer - not C pointer that cause a panic

- cmd/codegen/arguments_wrapper.go
- cmd/codegen/enum_deffinition.go
- cmd/codegen/function_deffiniton.go
- cmd/codegen/gencpp.go
- cmd/codegen/gengo.go
- cmd/codegen/gengo_enums.go
- cmd/codegen/gengo_funcs.go
- cmd/codegen/gengo_structs.go
- cmd/codegen/helpers.go
- cmd/codegen/main.go
- cmd/codegen/return_wrapper.go
- cmd/codegen/structures_deffinition.go
add GoIdentifier and CIdentifier
I tought about this since some time and I think that codegen code will be a bit cleaner now
---
_Due to area of this PR I'm going to skip waiting for `Test Source Code / Run Go Unittests (*)` because it doesn't metter_
> codegen: introduce helper types to clearify code

- texture.go
this file does not rely on glfw stuff
https://github.com/AllenDang/cimgui-go/issues/41#issuecomment-1956086126
> texture.go: remove go:build directive

- cimgui_funcs.go
- cimmarkdown_funcs.go
- cimnodes_funcs.go
- cimplot_funcs.go
- cmd/codegen/arguments_wrapper.go
- cmd/codegen/flags.go
- cmd/codegen/gengo_funcs.go
- cmd/codegen/gengo_typedefs.go
- cmd/codegen/helpers.go
- cmd/codegen/main.go
- cmd/codegen/return_wrapper.go
We all love object programming right? :smile:
I've organised `main.go` int a few, handy objects.
One of these objects called `Context` is passed through the whole generator (instead of a bunch of maps).
Also, now all generators uses maps by default so that checking if certain name is present in map is super easy.
> Codegen refactor

- texture.go
in some cases, 0 could be still a valid texture pointer
> texture: remove 0 check

- examples/main.go
If you're using this example code as the base for a project and start running other code in goroutines and getting the scheduler involved, the C bindings do not like this very much and the GUI will completely lock up when the scheduler automatically switches the imgui calls between OS threads.
> Add OS thread locking in example code

- glfw_backend.cpp
Hello @AllenDang, thanks for your awesome library. I found a potential bug related to memory management.
The `glfwImages` array allocated with malloc was not being freed. Since [`glfwSetWindowIcon` copies the images passed in before it returns](https://www.glfw.org/docs/latest/group__window.html#gadd7ccd39fe7a7d1f0904666ae5932dc5) (so this pointer is not managed by glfw, we should do it), this could lead to memory leaks. This commit fixes it.
Appendix:
> Fix memory leak in igGLFWWindow_SetIcon

- .github/workflows/golangci-lint.yaml
- .github/workflows/test.yaml
go.mod declares 1.22; 1.21 is no longer suitable (despite it worked fine because go downloads correct toolchain version now automatically)
> workflows: update go to 1.23

- internal/datautils/type_wrapper.go
this was necessary because of https://github.com/golang/go/issues/62356 fix #213
> datautils: remove tryPin part of WrapVoidPtr

- backend/sdlbackend/sdl_backend.cpp
- backend/sdlbackend/sdl_backend.go
imgui.MousePos returns global positions in the SDL backend, so it makes sense that SetCursor would accept the same position.  Typically used to lock a mouse in place.
> Change the SDL backend of SetCursor to accept global positions.

- backend/glfwbackend/glfw_backend.cpp
- 08dd44f45c8cf20e23460ad79c451fd0d2731db2 **refactor(glfwbackend): move clear buffer before render loop**: allow end user to use OpenGL before render ImGui
- c5bb73897cd4752993e93710449596eb897a4025 **refactor(glfwbackend): keep glfw context after window creation**: allow end user to use OpenGL after window creation
>  refactor(glfwbackend): move clear buffer before render loop 

- backend/texture.go
now it does not free texture manually
reasons:
- this caused a crash whenever GC was taking its fingers to the texutre. Was caused by the fact that GC runs in its own goroutine and OpenGL doesn't like it for some reason Now user needs to handle texture freeing manually
fix #350
> backend/texture: change default texture impl

- backend/glfwbackend/glfw_backend.cpp
caused ERROR: ImGui_ImplOpenGL3_CreateDeviceObjects: failed to compile fragment shader! With GLSL: #version 130
> I've investigated a bit more to justify this:
it causes because giu uses mainthread to call Run() in mainthread.
possibly caused by the fact that CreateWindow might be called in another goroutine than Render loop
> hotfix(glfwbackend): revert part of #348

- datautils/type_wrapper.go
while debugging ImGuizmo it turned out that WrapNumberPtr didn't work at all
In short it took pointer X, dereferenced it, converted into valid C type and returned as pointer Y.
Now it forces pointer cast via ConvertCTypes function.
> hotfix(datautils): WrapNumberPtr now works as expected

- README.md
- cmd/codegen/arguments_wrapper.go
- imgui/cimgui_funcs.go
- imguizmo/cimguizmo_funcs.go
- implot/cimplot_funcs.go
reasons?
Theoritically speaking we have absolutly no way to determine whether the XXX* c type should
be treat as slice or a pointer in go.
Technically, it is much easier to convert slice to pointer (&(mySlice[0])) than pointer to slice.
> codegen: get rid of simplePtrSliceW 

- cmd/codegen/enum_deffinition.go
- cmd/codegen/gengo.go
- cmd/codegen/gengo_enums.go
- cmd/codegen/gengo_funcs.go
- cmd/codegen/main.go
- cmd/codegen/return_wrapper.go
- examples/common/common.go
- examples/ebiten-game-in-texture/main.go
- examples/ebiten-game/main.go
- imnodes/cimnodes_enums.go
- imnodes/cimnodes_funcs.go
- imnodes/cimnodes_typedefs.go
- implot/cimplot_enums.go
- implot/cimplot_funcs.go
- implot/cimplot_typedefs.go
> remove ImNodes/Plot prefixes

- Makefile
- cmd/codegen/arguments_wrapper.go
- cmd/codegen/cimgui-go-preset.json
- cmd/codegen/flags.go
- cmd/codegen/gencpp.go
- cmd/codegen/gengo.go
- cmd/codegen/gengo_callbacks.go
- cmd/codegen/gengo_enums.go
- cmd/codegen/gengo_funcs.go
- cmd/codegen/gengo_typedefs.go
- cmd/codegen/main.go
- cmd/codegen/presets.go
- cmd/codegen/return_wrapper.go
- cmd/codegen/structures_deffinition.go
What is this?
currently, `gengo.go` (and randomly other files) have various maps with hardcoded strings.
The purpose of this change is, to move all of them and store as a single object.
I've decided to split this into 2 parts:
- `presets.go` contains a go struct. Its instance is stored inside of a Context.
- `cimgu-go-preset.json` contains actual values compatible with cimgui-go.
Why?
- To put everything hard-coded in 1 place
- To make our codegen independent on hardcoded values (maybe someone will use it somewhere else?)
There is a new `codegen -preset` flag to set path for this json file.
> codegen: Add presets json support

- cmd/codegen/gencpp.go
- cmd/codegen/gengo_funcs.go
- imgui/cimgui_funcs.go
- immarkdown/cimmarkdown_funcs.go
mainly for defaultMarktownFormatCallback
> Codegen: fix unexported funcs

- cmd/codegen/gengo_callbacks.go
- immarkdown/cimmarkdown_typedefs.go
in this context & means "Take pointer of this while calling the callback" Interpreting that a plain value caused data corruption
> codegen: in non-pointer callbacks: interpret & as pointer

- cmd/codegen/arguments_wrapper.go
- cmd/codegen/gengo.go
- cmd/codegen/gengo_funcs.go
- cmd/codegen/gengo_typedefs.go
- cmd/codegen/main.go
- cmd/codegen/return_wrapper.go
- imgui/cimgui_funcs.go
- immarkdown/cimmarkdown_funcs.go
- imnodes/cimnodes_funcs.go
- implot/cimplot_funcs.go
This PR includes som general updates in codegen package. For example it removes unused fields from Context struct.
ref #375
> Codegen refactor and cleanup

- backend/backend.go
- backend/ebiten-backend/cimgui_backend_impl.go
- backend/ebiten-backend/ebiten_backend.go
- backend/glfwbackend/glfw_backend.go
- backend/sdlbackend/sdl_backend.go
- examples/ebiten-game-in-texture/main.go
- examples/ebiten/main.go
- examples/glfw/main.go
- examples/sdl/main.go
Unfortunately this is a breaking change (again...) but should make 'dynamic backend selection' easier.
also, this makes no sense here.
> change(backend): dont take Backend as an arg to WIndowCloseCallback

- cmd/codegen/cimgui-go-preset.json
- cmd/codegen/gengo_funcs.go
- cmd/codegen/helpers.go
- cmd/codegen/presets.go
this has no real usage at current codebase, but in a future PR I'm going to upgrade to the latest cimgui which adds freetype support.
I'll want to exclude this freetype support from go generation, as it adds more problems and we don't need it right now.
The easiest way to achive this is just disabling one particular file but that feature sounds useful in general for the generator
> feat(codegen): allow to skip files

- cmd/codegen/cimgui-go-preset.json
shouldn't affect anything else just removes warning.
> codegen(preset): fix json formatting

- .github/workflows/golangci-lint.yaml
> workflows(golangci): upgrade golangci-lint version to v2.1.6

- impl/glfw/additional_cflags.go
after a deeper look into mechanism of how linking works here I got the following conclusions:
- impl should not link glfw (and other shared objects) manually
- If it is imported without linked glfw, it crashes during compilation (expected)
- if you import glfwbackend or e.g. go-gl/glfw, it works fine
> impl/glfw: do NOT link libglfw3.a

- cmd/codegen/gengo.go
- cmd/codegen/presets.go
If name present in Replace table, no further changes will be done (including removing Get prefix)
part of #448
> fix(codegen): do not further modify names if Replace

- backend/ebiten-backend/ebiten_backend.go
After a consultation with @hajimehoshi on discord, turns out that the Super key is actually supported by ebiten. It is called KeyMeta* (which is further linked to glfw.Key*Super in the internal section of ebiten)
> ebitenbackend: add Super modifier support
